# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
          MY_ENV_VAR: 'my value'
          check: ${{ secrets.GITLAPUSER }}
          super_secret: ${{ secrets.token }}
    
    - run: |
          mkdir -p ./reports/junit/
          cp ./example/junit.xml ./reports/junit/
        # I can't find a way to make the branch name below dynamic, so we'l
        # need to remember to adjust it when working on features.
    - uses: check-run-reporter/action@master
      env:
          CHECK_RUN_REPORTER_LABEL: 'Unit Tests'
          CHECK_RUN_REPORTER_REPORT: 'reports/junit/**/*.xml'
          CHECK_RUN_REPORTER_TOKEN: ${{ secrets.CHECK_RUN_REPORTER_TOKEN }}
    
    - name: Printenv
      run: |
          echo 'The selected color is' $MY_ENV_VAR
          echo 'The selected color is' $super_secret
   
    - name: Install
      run: npm i
      
    - run: npm test -- --reporter=junit -o ./reports/junit/test.xml
    
    - name: check report
      run: curl "https://api.check-run-reporter.com/api/v1/submissions" \
            --user token:ae2c14e5-03ad-404f-a54c-267ecaab9bf2 \
            -X POST \
             -F report=@"./reports/junit/test.xml" \
              -F label="Unit Tests" \
               -F sha="$CIRCLE_SHA1" \
                -F root="$(pwd)
    
    - name: Publish
      run: npm run publish
      if: github.event == 'push'
